apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bankguard-app
  namespace: argocd
  annotations:
    # ========================================
    # ARGOCD IMAGE UPDATER
    # ========================================
    argocd-image-updater.argoproj.io/image-list: bankguard-api=ghcr.io/laurentmd5/bankguard-api
    argocd-image-updater.argoproj.io/bankguard-api.update-strategy: newest-build
    argocd-image-updater.argoproj.io/bankguard-api.allow-tags: regexp:^[a-f0-9]{7}$
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/bankguard-git-creds
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/git-branch: main

spec:
  project: default

  source:
    repoURL: https://github.com/laurentmd5/bankguard-api.git
    targetRevision: main
    path: gitops-manifests/apps/bankguard/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: bankguard-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
