# gitops-manifests/apps/bankguard/base/kustomization.yaml
# CONFIGURATION COMMUNE à dev, staging, prod
# Ne JAMAIS modifier directement - utiliser les overlays

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Ressources Kubernetes à inclure
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- serviceaccount.yaml

# Labels communs à toutes les ressources

# Images - seront overridées par les overlays
images:
- name: ghcr.io/laurentmd5/bankguard-api
  newTag: PLACEHOLDER
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: gitops
    app.kubernetes.io/name: bankguard-api
    app.kubernetes.io/part-of: bankguard-system
