name: BankGuard CI (Build & Push)

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout du code applicatif
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Préparer Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Login GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4️⃣ Build & Push image (TAG STABLE POUR DEV)
      - name: Build and push Docker image (latest-dev)
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/bankguard-api
          IMAGE_TAG=latest-dev

          echo "Building ${IMAGE_NAME}:${IMAGE_TAG}"

          docker build \
            -t ${IMAGE_NAME}:${IMAGE_TAG} \
            ./app

          docker push ${IMAGE_NAME}:${IMAGE_TAG}

      # 5️⃣  Log clair pour audit
      - name: Image pushed successfully
        run: |
          echo "✅ Image ghcr.io/${{ github.repository_owner }}/bankguard-api:latest-dev pushed"
